# Generated by Django 5.0.2 on 2024-02-22 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_usuario_managers_usuario_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelTable(
            name='persona',
            table='Persona',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
