# Generated by Django 5.0.2 on 2024-02-27 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_usuario_options_alter_persona_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('identidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registro.persona')),
            ],
            options={
                'db_table': 'Empleado',
            },
        ),
    ]
